//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutAssistant.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public int PersonId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<int> Jersey { get; set; }
        public string Eligibility { get; set; }
        public string HometownCity { get; set; }
        public string HometownState { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public string Position { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual School School { get; set; }
    }
}
