//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutAssistant.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchoolPlayerList
    {
        public int SchoolId { get; set; }
        public int PersonId { get; set; }
        public int PlayerId { get; set; }
        public string SchoolCode { get; set; }
        public int ScoutArea { get; set; }
        public string SchoolName { get; set; }
        public string GreenBookName { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> Jersey { get; set; }
        public string Eligibility { get; set; }
        public string HometownCity { get; set; }
        public string HometownState { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public string Position { get; set; }
        public System.DateTime PlayerDateModified { get; set; }
        public System.DateTime PersonDateModified { get; set; }
    }
}
