//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutAssistant.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchoolFullList
    {
        public string SchoolCode { get; set; }
        public int ScoutArea { get; set; }
        public string School { get; set; }
        public int ESPN_ID { get; set; }
        public string SchoolShortName { get; set; }
        public string GreenBookName { get; set; }
        public string NickName { get; set; }
        public string Association { get; set; }
        public string Division { get; set; }
        public string Conference { get; set; }
        public string QuestionaireFileName { get; set; }
        public string AddressLine1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string HeadCoachName { get; set; }
        public string HeadCoachPhone { get; set; }
        public string HeadCoachEmail { get; set; }
        public string AssistantCoaches { get; set; }
        public string AssistantPhone { get; set; }
        public string VideoDirector { get; set; }
        public string VideoDirPhone { get; set; }
        public string AthleticDir { get; set; }
        public string AthleticDirPhone { get; set; }
        public string AthleticDirEmail { get; set; }
        public string AthleticDirFax { get; set; }
        public string SportsInfoDir { get; set; }
        public string SIDPhone { get; set; }
        public string SIDFax { get; set; }
        public string SIDEmail { get; set; }
        public string Trainer { get; set; }
        public string TrainerPhone { get; set; }
        public string StrengthCoach { get; set; }
        public string StrCoachPhone { get; set; }
        public string EquipManager { get; set; }
        public string EquipManagerPhone { get; set; }
        public string PressBoxPhone { get; set; }
        public Nullable<int> NationalGradedPlayers { get; set; }
        public Nullable<int> FalconsGradedPlayers { get; set; }
        public Nullable<int> PrimaryScoutID { get; set; }
        public Nullable<int> SecondaryScoutID { get; set; }
        public string BowlGame { get; set; }
        public Nullable<System.DateTime> GradDate { get; set; }
        public string HomeField { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Surface { get; set; }
        public string SchoolColors { get; set; }
        public string FBWebsite { get; set; }
        public bool TransmitFlag { get; set; }
        public Nullable<System.DateTime> BowlGameDate { get; set; }
        public string BowlGameText { get; set; }
        public string BowlGameOpponent { get; set; }
        public string BowlGameTV { get; set; }
        public bool IsNew { get; set; }
        public Nullable<System.DateTime> WorkoutDate { get; set; }
        public Nullable<System.DateTime> WorkoutDate2 { get; set; }
        public string ProLiaison { get; set; }
        public string ProLiaisonPhone { get; set; }
        public string Secretary { get; set; }
        public string SecretaryPhone { get; set; }
        public string PrimaryAreaScoutID { get; set; }
        public string RegionalScoutID { get; set; }
        public string Misc1 { get; set; }
        public string Misc2 { get; set; }
        public string Misc3 { get; set; }
        public string RivalsURL { get; set; }
        public string RivalsAltURL { get; set; }
        public string Comments { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public bool BCSSchool { get; set; }
        public bool HideBirthdate { get; set; }
        public int NFLSchoolID { get; set; }
        public string Notes { get; set; }
        public string Restrictions { get; set; }
        public string ClosedDates { get; set; }
        public string InSeasonSchedule { get; set; }
        public Nullable<System.DateTime> RestrictionsCompleted { get; set; }
        public string RestrictionsCompletedBy { get; set; }
        public string FootballAddress { get; set; }
        public bool isAPT { get; set; }
        public string APTClub { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool HBCU { get; set; }
    }
}
