//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutAssistant.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchoolPartialList
    {
        public string SchoolCode { get; set; }
        public int ScoutArea { get; set; }
        public string School { get; set; }
        public string SchoolShortName { get; set; }
        public string GreenBookName { get; set; }
        public string NickName { get; set; }
        public string Association { get; set; }
        public string Division { get; set; }
        public string Conference { get; set; }
        public string QuestionaireFileName { get; set; }
        public string SchoolAddress { get; set; }
        public string FootballAddress { get; set; }
        public string HeadCoachName { get; set; }
        public string AssistantCoaches { get; set; }
        public string VideoDirector { get; set; }
        public string AthleticDir { get; set; }
        public string SportsInfoDir { get; set; }
        public string ProLiaison { get; set; }
        public Nullable<int> NationalGradedPlayers { get; set; }
        public Nullable<int> FalconsGradedPlayers { get; set; }
        public Nullable<System.DateTime> WorkoutDate { get; set; }
        public Nullable<System.DateTime> WorkoutDate2 { get; set; }
        public Nullable<int> PrimaryScoutID { get; set; }
        public Nullable<int> SecondaryScoutID { get; set; }
        public string PrimaryAreaScoutID { get; set; }
        public string RegionalScoutID { get; set; }
        public string FBWebsite { get; set; }
        public string RivalsURL { get; set; }
        public string RivalsAltURL { get; set; }
        public int NFLSchoolID { get; set; }
        public int ESPN_ID { get; set; }
    }
}
